import {
  User,
  Quiz,
  Question,
  QuizCategory,
  QuizAttempt,
  LeaderboardEntry,
  Achievement,
  Notification,
  DashboardStats,
} from '@/lib/types';

// =============================================================================
// USERS
// =============================================================================

export const users: User[] = [
  {
    id: 'user-1',
    email: 'admin@example.com',
    password: 'admin123',
    name: 'Alex Thompson',
    role: 'admin',
    avatar: '',
    bio: 'Platform administrator and quiz enthusiast',
    status: 'active',
    stats: {
      quizzesTaken: 45,
      averageScore: 88,
      totalPoints: 12500,
      rank: 1,
      streak: 15,
      bestCategory: 'Programming',
    },
    createdAt: '2024-01-15T10:00:00Z',
    lastLogin: '2024-03-05T09:00:00Z',
  },
  {
    id: 'user-2',
    email: 'sarah@example.com',
    password: 'sarah123',
    name: 'Sarah Chen',
    role: 'instructor',
    avatar: '',
    bio: 'Science teacher with 10 years of experience',
    status: 'active',
    stats: {
      quizzesTaken: 38,
      averageScore: 92,
      totalPoints: 11200,
      rank: 2,
      streak: 12,
      bestCategory: 'Science',
    },
    createdAt: '2024-01-20T10:00:00Z',
    lastLogin: '2024-03-04T14:00:00Z',
  },
  {
    id: 'user-3',
    email: 'james@example.com',
    password: 'james123',
    name: 'James Wilson',
    role: 'user',
    avatar: '',
    bio: 'Mathematics student and aspiring data scientist',
    status: 'active',
    stats: {
      quizzesTaken: 29,
      averageScore: 76,
      totalPoints: 8400,
      rank: 4,
      streak: 7,
      bestCategory: 'Mathematics',
    },
    createdAt: '2024-01-25T10:00:00Z',
    lastLogin: '2024-03-03T16:00:00Z',
  },
  {
    id: 'user-4',
    email: 'maria@example.com',
    password: 'maria123',
    name: 'Maria Garcia',
    role: 'user',
    avatar: '',
    bio: 'History buff and trivia lover',
    status: 'active',
    stats: {
      quizzesTaken: 22,
      averageScore: 81,
      totalPoints: 7600,
      rank: 5,
      streak: 5,
      bestCategory: 'History',
    },
    createdAt: '2024-02-01T10:00:00Z',
    lastLogin: '2024-03-04T11:00:00Z',
  },
  {
    id: 'user-5',
    email: 'david@example.com',
    password: 'david123',
    name: 'David Kim',
    role: 'instructor',
    avatar: '',
    bio: 'Senior software engineer and coding instructor',
    status: 'active',
    stats: {
      quizzesTaken: 41,
      averageScore: 94,
      totalPoints: 10800,
      rank: 3,
      streak: 20,
      bestCategory: 'Programming',
    },
    createdAt: '2024-01-18T10:00:00Z',
    lastLogin: '2024-03-05T08:00:00Z',
  },
  {
    id: 'user-6',
    email: 'emily@example.com',
    password: 'emily123',
    name: 'Emily Johnson',
    role: 'user',
    avatar: '',
    bio: 'English literature graduate and word nerd',
    status: 'active',
    stats: {
      quizzesTaken: 18,
      averageScore: 85,
      totalPoints: 6200,
      rank: 6,
      streak: 3,
      bestCategory: 'Language',
    },
    createdAt: '2024-02-05T10:00:00Z',
    lastLogin: '2024-03-02T20:00:00Z',
  },
  {
    id: 'user-7',
    email: 'ryan@example.com',
    password: 'ryan123',
    name: 'Ryan Park',
    role: 'user',
    avatar: '',
    bio: 'Pre-med student with a passion for biology',
    status: 'active',
    stats: {
      quizzesTaken: 15,
      averageScore: 70,
      totalPoints: 4800,
      rank: 7,
      streak: 2,
      bestCategory: 'Science',
    },
    createdAt: '2024-02-10T10:00:00Z',
    lastLogin: '2024-03-01T18:00:00Z',
  },
  {
    id: 'user-8',
    email: 'olivia@example.com',
    password: 'olivia123',
    name: 'Olivia Brown',
    role: 'user',
    avatar: '',
    bio: 'Lifelong learner interested in everything',
    status: 'active',
    stats: {
      quizzesTaken: 12,
      averageScore: 68,
      totalPoints: 3500,
      rank: 8,
      streak: 1,
      bestCategory: 'General Knowledge',
    },
    createdAt: '2024-02-15T10:00:00Z',
    lastLogin: '2024-02-28T15:00:00Z',
  },
];

// =============================================================================
// CATEGORIES
// =============================================================================

export const categories: QuizCategory[] = [
  {
    id: 'cat-1',
    name: 'Science',
    slug: 'science',
    icon: 'Microscope',
    description: 'Physics, Chemistry, Biology',
    color: 'bg-blue-500',
    quizCount: 3,
  },
  {
    id: 'cat-2',
    name: 'Mathematics',
    slug: 'mathematics',
    icon: 'Calculator',
    description: 'Algebra, Geometry, Calculus',
    color: 'bg-green-500',
    quizCount: 2,
  },
  {
    id: 'cat-3',
    name: 'Programming',
    slug: 'programming',
    icon: 'Code',
    description: 'JavaScript, Python, React',
    color: 'bg-purple-500',
    quizCount: 3,
  },
  {
    id: 'cat-4',
    name: 'History',
    slug: 'history',
    icon: 'BookOpen',
    description: 'World History, Civilizations',
    color: 'bg-amber-500',
    quizCount: 2,
  },
  {
    id: 'cat-5',
    name: 'Language',
    slug: 'language',
    icon: 'Languages',
    description: 'English, Grammar, Vocabulary',
    color: 'bg-pink-500',
    quizCount: 1,
  },
  {
    id: 'cat-6',
    name: 'General Knowledge',
    slug: 'general-knowledge',
    icon: 'Globe',
    description: 'Trivia, Current Affairs',
    color: 'bg-cyan-500',
    quizCount: 1,
  },
];

// =============================================================================
// QUESTIONS
// =============================================================================

export const questions: Question[] = [
  // ---------------------------------------------------------------------------
  // PHYSICS FUNDAMENTALS (quiz-1) — q-1 through q-8
  // ---------------------------------------------------------------------------
  {
    id: 'q-1',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the SI unit of force?',
    options: [
      { id: 'q1-a', text: 'Joule', isCorrect: false },
      { id: 'q1-b', text: 'Newton', isCorrect: true },
      { id: 'q1-c', text: 'Watt', isCorrect: false },
      { id: 'q1-d', text: 'Pascal', isCorrect: false },
    ],
    explanation: 'The Newton (N) is the SI unit of force, named after Sir Isaac Newton. One Newton is the force needed to accelerate one kilogram of mass at one meter per second squared.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-2',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'Which of Newton\'s laws states that every action has an equal and opposite reaction?',
    options: [
      { id: 'q2-a', text: 'First Law', isCorrect: false },
      { id: 'q2-b', text: 'Second Law', isCorrect: false },
      { id: 'q2-c', text: 'Third Law', isCorrect: true },
      { id: 'q2-d', text: 'Law of Universal Gravitation', isCorrect: false },
    ],
    explanation: 'Newton\'s Third Law of Motion states that for every action, there is an equal and opposite reaction. When one body exerts a force on a second body, the second body exerts an equal force in the opposite direction on the first body.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-3',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'true-false',
    text: 'The speed of light in a vacuum is approximately 3 × 10⁸ meters per second.',
    options: [
      { id: 'q3-a', text: 'True', isCorrect: true },
      { id: 'q3-b', text: 'False', isCorrect: false },
    ],
    explanation: 'The speed of light in a vacuum is approximately 299,792,458 meters per second, which is commonly rounded to 3 × 10⁸ m/s.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-4',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the formula for kinetic energy?',
    options: [
      { id: 'q4-a', text: 'KE = mgh', isCorrect: false },
      { id: 'q4-b', text: 'KE = ½mv²', isCorrect: true },
      { id: 'q4-c', text: 'KE = Fd', isCorrect: false },
      { id: 'q4-d', text: 'KE = mv', isCorrect: false },
    ],
    explanation: 'Kinetic energy is the energy of motion and is calculated as KE = ½mv², where m is the mass of the object and v is its velocity.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-5',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What phenomenon explains why a rainbow forms?',
    options: [
      { id: 'q5-a', text: 'Reflection', isCorrect: false },
      { id: 'q5-b', text: 'Diffraction', isCorrect: false },
      { id: 'q5-c', text: 'Dispersion', isCorrect: true },
      { id: 'q5-d', text: 'Interference', isCorrect: false },
    ],
    explanation: 'A rainbow forms due to the dispersion of sunlight by water droplets. White light is separated into its component colors because each wavelength is refracted at a slightly different angle.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-6',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'true-false',
    text: 'Sound travels faster in water than in air.',
    options: [
      { id: 'q6-a', text: 'True', isCorrect: true },
      { id: 'q6-b', text: 'False', isCorrect: false },
    ],
    explanation: 'Sound travels approximately 4.3 times faster in water (~1,480 m/s) than in air (~343 m/s) because water molecules are packed more closely together, allowing vibrations to transfer more quickly.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-7',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'multi-select',
    text: 'Which of the following are forms of energy? (Select all that apply)',
    options: [
      { id: 'q7-a', text: 'Kinetic energy', isCorrect: true },
      { id: 'q7-b', text: 'Thermal energy', isCorrect: true },
      { id: 'q7-c', text: 'Velocity energy', isCorrect: false },
      { id: 'q7-d', text: 'Potential energy', isCorrect: true },
    ],
    explanation: 'Kinetic, thermal, and potential energy are all recognized forms of energy. "Velocity energy" is not a standard physics term; velocity is a component used to calculate kinetic energy.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-8',
    quizId: 'quiz-1',
    categoryId: 'cat-1',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the acceleration due to gravity on Earth\'s surface?',
    options: [
      { id: 'q8-a', text: '8.9 m/s²', isCorrect: false },
      { id: 'q8-b', text: '9.8 m/s²', isCorrect: true },
      { id: 'q8-c', text: '10.8 m/s²', isCorrect: false },
      { id: 'q8-d', text: '11.2 m/s²', isCorrect: false },
    ],
    explanation: 'The standard acceleration due to gravity on Earth\'s surface is approximately 9.8 m/s² (often rounded to 9.81 m/s²). This value varies slightly depending on altitude and latitude.',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // CHEMISTRY BASICS (quiz-2) — q-9 through q-16
  // ---------------------------------------------------------------------------
  {
    id: 'q-9',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the chemical symbol for gold?',
    options: [
      { id: 'q9-a', text: 'Go', isCorrect: false },
      { id: 'q9-b', text: 'Gd', isCorrect: false },
      { id: 'q9-c', text: 'Au', isCorrect: true },
      { id: 'q9-d', text: 'Ag', isCorrect: false },
    ],
    explanation: 'The chemical symbol for gold is Au, derived from the Latin word "aurum" meaning "shining dawn." Ag is the symbol for silver (from Latin "argentum").',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-10',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the pH of pure water at 25°C?',
    options: [
      { id: 'q10-a', text: '0', isCorrect: false },
      { id: 'q10-b', text: '5', isCorrect: false },
      { id: 'q10-c', text: '7', isCorrect: true },
      { id: 'q10-d', text: '14', isCorrect: false },
    ],
    explanation: 'Pure water at 25°C has a pH of 7, which is considered neutral on the pH scale. Values below 7 are acidic and values above 7 are basic (alkaline).',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-11',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'true-false',
    text: 'An atom\'s atomic number is determined by the number of protons in its nucleus.',
    options: [
      { id: 'q11-a', text: 'True', isCorrect: true },
      { id: 'q11-b', text: 'False', isCorrect: false },
    ],
    explanation: 'The atomic number of an element is defined as the number of protons in the nucleus of an atom. This number uniquely identifies a chemical element and determines its place in the periodic table.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-12',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'Which gas makes up approximately 78% of Earth\'s atmosphere?',
    options: [
      { id: 'q12-a', text: 'Oxygen', isCorrect: false },
      { id: 'q12-b', text: 'Carbon Dioxide', isCorrect: false },
      { id: 'q12-c', text: 'Nitrogen', isCorrect: true },
      { id: 'q12-d', text: 'Argon', isCorrect: false },
    ],
    explanation: 'Nitrogen (N₂) makes up approximately 78% of Earth\'s atmosphere by volume. Oxygen makes up about 21%, with argon and other gases making up the remaining ~1%.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-13',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multi-select',
    text: 'Which of the following are noble gases? (Select all that apply)',
    options: [
      { id: 'q13-a', text: 'Helium', isCorrect: true },
      { id: 'q13-b', text: 'Chlorine', isCorrect: false },
      { id: 'q13-c', text: 'Neon', isCorrect: true },
      { id: 'q13-d', text: 'Argon', isCorrect: true },
    ],
    explanation: 'Helium (He), Neon (Ne), and Argon (Ar) are all noble gases found in Group 18 of the periodic table. Chlorine (Cl) is a halogen in Group 17.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-14',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What type of bond involves the sharing of electron pairs between atoms?',
    options: [
      { id: 'q14-a', text: 'Ionic bond', isCorrect: false },
      { id: 'q14-b', text: 'Covalent bond', isCorrect: true },
      { id: 'q14-c', text: 'Metallic bond', isCorrect: false },
      { id: 'q14-d', text: 'Hydrogen bond', isCorrect: false },
    ],
    explanation: 'A covalent bond involves the sharing of electron pairs between atoms. Ionic bonds involve the transfer of electrons, metallic bonds involve a sea of delocalized electrons, and hydrogen bonds are weak intermolecular forces.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-15',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the chemical formula for table salt?',
    options: [
      { id: 'q15-a', text: 'NaOH', isCorrect: false },
      { id: 'q15-b', text: 'NaCl', isCorrect: true },
      { id: 'q15-c', text: 'KCl', isCorrect: false },
      { id: 'q15-d', text: 'CaCl₂', isCorrect: false },
    ],
    explanation: 'Table salt is sodium chloride with the chemical formula NaCl. It is an ionic compound formed from a sodium cation (Na⁺) and a chloride anion (Cl⁻).',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-16',
    quizId: 'quiz-2',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'true-false',
    text: 'Isotopes of an element have the same number of protons but different numbers of neutrons.',
    options: [
      { id: 'q16-a', text: 'True', isCorrect: true },
      { id: 'q16-b', text: 'False', isCorrect: false },
    ],
    explanation: 'Isotopes are variants of a chemical element that share the same number of protons (atomic number) but differ in the number of neutrons, resulting in different mass numbers.',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // BIOLOGY 101 (quiz-3) — q-17 through q-23
  // ---------------------------------------------------------------------------
  {
    id: 'q-17',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the powerhouse of the cell?',
    options: [
      { id: 'q17-a', text: 'Nucleus', isCorrect: false },
      { id: 'q17-b', text: 'Ribosome', isCorrect: false },
      { id: 'q17-c', text: 'Mitochondria', isCorrect: true },
      { id: 'q17-d', text: 'Endoplasmic Reticulum', isCorrect: false },
    ],
    explanation: 'Mitochondria are often called the "powerhouse of the cell" because they generate most of the cell\'s supply of adenosine triphosphate (ATP), the main energy currency of the cell.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-18',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What molecule carries genetic information in most living organisms?',
    options: [
      { id: 'q18-a', text: 'RNA', isCorrect: false },
      { id: 'q18-b', text: 'DNA', isCorrect: true },
      { id: 'q18-c', text: 'Protein', isCorrect: false },
      { id: 'q18-d', text: 'ATP', isCorrect: false },
    ],
    explanation: 'DNA (deoxyribonucleic acid) is the molecule that carries the genetic instructions for the development, functioning, growth, and reproduction of all known organisms.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-19',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'true-false',
    text: 'Photosynthesis occurs in the chloroplasts of plant cells.',
    options: [
      { id: 'q19-a', text: 'True', isCorrect: true },
      { id: 'q19-b', text: 'False', isCorrect: false },
    ],
    explanation: 'Photosynthesis takes place primarily in the chloroplasts. These organelles contain chlorophyll, the green pigment that absorbs light energy used to convert carbon dioxide and water into glucose and oxygen.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-20',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'How many chromosomes do humans typically have?',
    options: [
      { id: 'q20-a', text: '23', isCorrect: false },
      { id: 'q20-b', text: '44', isCorrect: false },
      { id: 'q20-c', text: '46', isCorrect: true },
      { id: 'q20-d', text: '48', isCorrect: false },
    ],
    explanation: 'Humans typically have 46 chromosomes arranged in 23 pairs. 22 pairs are autosomes and 1 pair are sex chromosomes (XX in females, XY in males).',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-21',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multi-select',
    text: 'Which of the following are parts of a plant cell but NOT an animal cell? (Select all that apply)',
    options: [
      { id: 'q21-a', text: 'Cell wall', isCorrect: true },
      { id: 'q21-b', text: 'Cell membrane', isCorrect: false },
      { id: 'q21-c', text: 'Chloroplasts', isCorrect: true },
      { id: 'q21-d', text: 'Large central vacuole', isCorrect: true },
    ],
    explanation: 'Plant cells have a cell wall, chloroplasts, and a large central vacuole that are not found in animal cells. Both plant and animal cells have a cell membrane.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-22',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the process by which cells divide to produce two identical daughter cells?',
    options: [
      { id: 'q22-a', text: 'Meiosis', isCorrect: false },
      { id: 'q22-b', text: 'Mitosis', isCorrect: true },
      { id: 'q22-c', text: 'Binary fission', isCorrect: false },
      { id: 'q22-d', text: 'Budding', isCorrect: false },
    ],
    explanation: 'Mitosis is the process of cell division that results in two genetically identical daughter cells. Meiosis produces four non-identical cells with half the chromosome number and is used for producing gametes.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-23',
    quizId: 'quiz-3',
    categoryId: 'cat-1',
    difficulty: 'easy',
    type: 'true-false',
    text: 'Viruses are considered living organisms.',
    options: [
      { id: 'q23-a', text: 'True', isCorrect: false },
      { id: 'q23-b', text: 'False', isCorrect: true },
    ],
    explanation: 'Viruses are generally not considered living organisms because they cannot reproduce independently, do not have cellular structure, and lack their own metabolism. They require a host cell to replicate.',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // ALGEBRA ESSENTIALS (quiz-4) — q-24 through q-30
  // ---------------------------------------------------------------------------
  {
    id: 'q-24',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the value of x in the equation 2x + 6 = 14?',
    options: [
      { id: 'q24-a', text: '3', isCorrect: false },
      { id: 'q24-b', text: '4', isCorrect: true },
      { id: 'q24-c', text: '5', isCorrect: false },
      { id: 'q24-d', text: '10', isCorrect: false },
    ],
    explanation: 'Solving 2x + 6 = 14: subtract 6 from both sides to get 2x = 8, then divide both sides by 2 to get x = 4.',
    points: 10,
    timeLimit: 45,
  },
  {
    id: 'q-25',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the slope of the line y = 3x - 7?',
    options: [
      { id: 'q25-a', text: '-7', isCorrect: false },
      { id: 'q25-b', text: '3', isCorrect: true },
      { id: 'q25-c', text: '7', isCorrect: false },
      { id: 'q25-d', text: '-3', isCorrect: false },
    ],
    explanation: 'In the slope-intercept form y = mx + b, m represents the slope and b represents the y-intercept. In y = 3x - 7, the slope m = 3 and the y-intercept b = -7.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-26',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'true-false',
    text: 'The quadratic formula is x = (-b ± √(b² - 4ac)) / 2a.',
    options: [
      { id: 'q26-a', text: 'True', isCorrect: true },
      { id: 'q26-b', text: 'False', isCorrect: false },
    ],
    explanation: 'The quadratic formula x = (-b ± √(b² - 4ac)) / 2a is used to solve quadratic equations of the form ax² + bx + c = 0. The expression b² - 4ac is called the discriminant.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-27',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What are the solutions to x² - 9 = 0?',
    options: [
      { id: 'q27-a', text: 'x = 3 only', isCorrect: false },
      { id: 'q27-b', text: 'x = -3 only', isCorrect: false },
      { id: 'q27-c', text: 'x = 3 and x = -3', isCorrect: true },
      { id: 'q27-d', text: 'x = 9 and x = -9', isCorrect: false },
    ],
    explanation: 'x² - 9 = 0 can be factored as (x + 3)(x - 3) = 0 using the difference of squares. Setting each factor to zero gives x = 3 and x = -3.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-28',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'Simplify: (3x²)(4x³)',
    options: [
      { id: 'q28-a', text: '7x⁵', isCorrect: false },
      { id: 'q28-b', text: '12x⁵', isCorrect: true },
      { id: 'q28-c', text: '12x⁶', isCorrect: false },
      { id: 'q28-d', text: '7x⁶', isCorrect: false },
    ],
    explanation: 'When multiplying terms with the same base, multiply the coefficients and add the exponents: (3)(4) = 12 and x^(2+3) = x⁵, giving 12x⁵.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-29',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'multi-select',
    text: 'Which of the following are properties of logarithms? (Select all that apply)',
    options: [
      { id: 'q29-a', text: 'log(ab) = log(a) + log(b)', isCorrect: true },
      { id: 'q29-b', text: 'log(a/b) = log(a) - log(b)', isCorrect: true },
      { id: 'q29-c', text: 'log(a + b) = log(a) × log(b)', isCorrect: false },
      { id: 'q29-d', text: 'log(aⁿ) = n × log(a)', isCorrect: true },
    ],
    explanation: 'The three fundamental properties of logarithms are: the product rule log(ab) = log(a) + log(b), the quotient rule log(a/b) = log(a) - log(b), and the power rule log(aⁿ) = n × log(a). There is no simple rule for log(a + b).',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-30',
    quizId: 'quiz-4',
    categoryId: 'cat-2',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the value of 5! (5 factorial)?',
    options: [
      { id: 'q30-a', text: '25', isCorrect: false },
      { id: 'q30-b', text: '60', isCorrect: false },
      { id: 'q30-c', text: '120', isCorrect: true },
      { id: 'q30-d', text: '720', isCorrect: false },
    ],
    explanation: '5! = 5 × 4 × 3 × 2 × 1 = 120. Factorial is the product of all positive integers less than or equal to n.',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // GEOMETRY CHALLENGE (quiz-5) — q-31 through q-36
  // ---------------------------------------------------------------------------
  {
    id: 'q-31',
    quizId: 'quiz-5',
    categoryId: 'cat-2',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What is the sum of interior angles in a triangle?',
    options: [
      { id: 'q31-a', text: '90°', isCorrect: false },
      { id: 'q31-b', text: '180°', isCorrect: true },
      { id: 'q31-c', text: '270°', isCorrect: false },
      { id: 'q31-d', text: '360°', isCorrect: false },
    ],
    explanation: 'The sum of the interior angles in any triangle is always 180 degrees. This is a fundamental theorem in Euclidean geometry.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-32',
    quizId: 'quiz-5',
    categoryId: 'cat-2',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What is the area of a circle with radius 5?',
    options: [
      { id: 'q32-a', text: '10π', isCorrect: false },
      { id: 'q32-b', text: '25π', isCorrect: true },
      { id: 'q32-c', text: '50π', isCorrect: false },
      { id: 'q32-d', text: '5π', isCorrect: false },
    ],
    explanation: 'The area of a circle is A = πr². With r = 5, A = π(5²) = 25π square units.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-33',
    quizId: 'quiz-5',
    categoryId: 'cat-2',
    difficulty: 'hard',
    type: 'true-false',
    text: 'The Pythagorean theorem states that in a right triangle, a² + b² = c², where c is the hypotenuse.',
    options: [
      { id: 'q33-a', text: 'True', isCorrect: true },
      { id: 'q33-b', text: 'False', isCorrect: false },
    ],
    explanation: 'The Pythagorean theorem states that in a right-angled triangle, the square of the length of the hypotenuse (c) equals the sum of the squares of the other two sides (a and b): a² + b² = c².',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-34',
    quizId: 'quiz-5',
    categoryId: 'cat-2',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'A regular hexagon has how many lines of symmetry?',
    options: [
      { id: 'q34-a', text: '3', isCorrect: false },
      { id: 'q34-b', text: '4', isCorrect: false },
      { id: 'q34-c', text: '6', isCorrect: true },
      { id: 'q34-d', text: '8', isCorrect: false },
    ],
    explanation: 'A regular hexagon has 6 lines of symmetry: 3 lines connecting opposite vertices and 3 lines connecting midpoints of opposite sides.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-35',
    quizId: 'quiz-5',
    categoryId: 'cat-2',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What is the volume of a sphere with radius 3? (Use V = 4/3πr³)',
    options: [
      { id: 'q35-a', text: '27π', isCorrect: false },
      { id: 'q35-b', text: '36π', isCorrect: true },
      { id: 'q35-c', text: '108π', isCorrect: false },
      { id: 'q35-d', text: '12π', isCorrect: false },
    ],
    explanation: 'V = (4/3)πr³ = (4/3)π(3³) = (4/3)π(27) = 36π cubic units.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-36',
    quizId: 'quiz-5',
    categoryId: 'cat-2',
    difficulty: 'hard',
    type: 'multi-select',
    text: 'Which of the following are properties of a parallelogram? (Select all that apply)',
    options: [
      { id: 'q36-a', text: 'Opposite sides are parallel', isCorrect: true },
      { id: 'q36-b', text: 'All angles are 90°', isCorrect: false },
      { id: 'q36-c', text: 'Opposite angles are equal', isCorrect: true },
      { id: 'q36-d', text: 'Diagonals bisect each other', isCorrect: true },
    ],
    explanation: 'In a parallelogram, opposite sides are parallel, opposite angles are equal, and the diagonals bisect each other. Not all angles are necessarily 90° (that would specifically be a rectangle).',
    points: 20,
    timeLimit: 60,
  },

  // ---------------------------------------------------------------------------
  // JAVASCRIPT MASTERY (quiz-6) — q-37 through q-44
  // ---------------------------------------------------------------------------
  {
    id: 'q-37',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What does "typeof null" return in JavaScript?',
    options: [
      { id: 'q37-a', text: '"null"', isCorrect: false },
      { id: 'q37-b', text: '"undefined"', isCorrect: false },
      { id: 'q37-c', text: '"object"', isCorrect: true },
      { id: 'q37-d', text: '"boolean"', isCorrect: false },
    ],
    explanation: 'In JavaScript, typeof null returns "object". This is a well-known bug from the first version of JavaScript where values were represented as a type tag and a value, and the type tag for objects was 0, which was also the value for null.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-38',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What is the output of: console.log(0.1 + 0.2 === 0.3)?',
    options: [
      { id: 'q38-a', text: 'true', isCorrect: false },
      { id: 'q38-b', text: 'false', isCorrect: true },
      { id: 'q38-c', text: 'undefined', isCorrect: false },
      { id: 'q38-d', text: 'NaN', isCorrect: false },
    ],
    explanation: 'Due to floating-point precision in JavaScript (IEEE 754), 0.1 + 0.2 equals 0.30000000000000004, not exactly 0.3. Therefore the strict equality comparison returns false.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-39',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'true-false',
    text: 'In JavaScript, "let" and "const" declarations are hoisted but not initialized.',
    options: [
      { id: 'q39-a', text: 'True', isCorrect: true },
      { id: 'q39-b', text: 'False', isCorrect: false },
    ],
    explanation: 'Variables declared with let and const are hoisted to the top of their block scope but are not initialized. Accessing them before their declaration results in a ReferenceError, known as the "temporal dead zone."',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-40',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What does the Array.prototype.reduce() method do?',
    options: [
      { id: 'q40-a', text: 'Removes elements from an array', isCorrect: false },
      { id: 'q40-b', text: 'Filters elements based on a condition', isCorrect: false },
      { id: 'q40-c', text: 'Executes a reducer function on each element, resulting in a single output value', isCorrect: true },
      { id: 'q40-d', text: 'Creates a new array with transformed elements', isCorrect: false },
    ],
    explanation: 'The reduce() method executes a user-supplied "reducer" callback function on each element of the array, passing in the return value from the calculation on the preceding element, resulting in a single value.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-41',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'multi-select',
    text: 'Which of the following are falsy values in JavaScript? (Select all that apply)',
    options: [
      { id: 'q41-a', text: '0', isCorrect: true },
      { id: 'q41-b', text: '"" (empty string)', isCorrect: true },
      { id: 'q41-c', text: '[] (empty array)', isCorrect: false },
      { id: 'q41-d', text: 'null', isCorrect: true },
    ],
    explanation: 'In JavaScript, the falsy values are: false, 0, -0, 0n, "" (empty string), null, undefined, and NaN. An empty array [] is truthy because it is an object.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-42',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What is the difference between "==" and "===" in JavaScript?',
    options: [
      { id: 'q42-a', text: 'No difference, they are interchangeable', isCorrect: false },
      { id: 'q42-b', text: '"==" checks value only, "===" checks value and type', isCorrect: true },
      { id: 'q42-c', text: '"===" checks value only, "==" checks value and type', isCorrect: false },
      { id: 'q42-d', text: '"==" is used for numbers, "===" is used for strings', isCorrect: false },
    ],
    explanation: 'The "==" operator performs type coercion before comparison (abstract equality), while "===" performs strict equality comparison without type coercion, checking both value and type.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-43',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'multiple-choice',
    text: 'What does the "spread operator" (...) do when used with an array?',
    options: [
      { id: 'q43-a', text: 'Deletes all elements in the array', isCorrect: false },
      { id: 'q43-b', text: 'Expands an iterable into individual elements', isCorrect: true },
      { id: 'q43-c', text: 'Converts the array to a string', isCorrect: false },
      { id: 'q43-d', text: 'Sorts the array elements', isCorrect: false },
    ],
    explanation: 'The spread operator (...) expands an iterable (like an array) into individual elements. It is commonly used for copying arrays, merging arrays, and passing array elements as function arguments.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-44',
    quizId: 'quiz-6',
    categoryId: 'cat-3',
    difficulty: 'hard',
    type: 'true-false',
    text: 'Promises in JavaScript can be in one of three states: pending, fulfilled, or rejected.',
    options: [
      { id: 'q44-a', text: 'True', isCorrect: true },
      { id: 'q44-b', text: 'False', isCorrect: false },
    ],
    explanation: 'A Promise in JavaScript is always in one of three states: pending (initial state, neither fulfilled nor rejected), fulfilled (the operation completed successfully), or rejected (the operation failed).',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // REACT FUNDAMENTALS (quiz-7) — q-45 through q-51
  // ---------------------------------------------------------------------------
  {
    id: 'q-45',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What hook is used to manage state in a React functional component?',
    options: [
      { id: 'q45-a', text: 'useEffect', isCorrect: false },
      { id: 'q45-b', text: 'useState', isCorrect: true },
      { id: 'q45-c', text: 'useContext', isCorrect: false },
      { id: 'q45-d', text: 'useRef', isCorrect: false },
    ],
    explanation: 'useState is the React hook used to add state to functional components. It returns a stateful value and a function to update it.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-46',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the virtual DOM in React?',
    options: [
      { id: 'q46-a', text: 'A complete copy of the browser DOM stored on the server', isCorrect: false },
      { id: 'q46-b', text: 'A lightweight JavaScript representation of the actual DOM', isCorrect: true },
      { id: 'q46-c', text: 'A CSS framework for styling React components', isCorrect: false },
      { id: 'q46-d', text: 'A database for storing component state', isCorrect: false },
    ],
    explanation: 'The virtual DOM is a lightweight JavaScript representation of the actual DOM. React uses it to efficiently determine what changes need to be made to the real DOM by comparing the previous and current virtual DOM trees (a process called "reconciliation").',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-47',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'true-false',
    text: 'In React, props are read-only and cannot be modified by the child component.',
    options: [
      { id: 'q47-a', text: 'True', isCorrect: true },
      { id: 'q47-b', text: 'False', isCorrect: false },
    ],
    explanation: 'Props in React follow a unidirectional data flow. They are read-only and should not be modified by the child component. If a child needs to communicate changes, it should use callback functions passed as props.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-48',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What does the useEffect hook do in React?',
    options: [
      { id: 'q48-a', text: 'Manages component state', isCorrect: false },
      { id: 'q48-b', text: 'Performs side effects in functional components', isCorrect: true },
      { id: 'q48-c', text: 'Provides context to child components', isCorrect: false },
      { id: 'q48-d', text: 'Memoizes expensive calculations', isCorrect: false },
    ],
    explanation: 'useEffect is used to perform side effects in functional components, such as data fetching, setting up subscriptions, and manually changing the DOM. It runs after the component renders.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-49',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'multi-select',
    text: 'Which of the following are valid React hooks? (Select all that apply)',
    options: [
      { id: 'q49-a', text: 'useMemo', isCorrect: true },
      { id: 'q49-b', text: 'useCallback', isCorrect: true },
      { id: 'q49-c', text: 'useRender', isCorrect: false },
      { id: 'q49-d', text: 'useReducer', isCorrect: true },
    ],
    explanation: 'useMemo, useCallback, and useReducer are all built-in React hooks. useMemo memoizes computed values, useCallback memoizes functions, and useReducer manages complex state logic. There is no built-in "useRender" hook.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-50',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is JSX in React?',
    options: [
      { id: 'q50-a', text: 'A separate programming language', isCorrect: false },
      { id: 'q50-b', text: 'A syntax extension that allows writing HTML-like code in JavaScript', isCorrect: true },
      { id: 'q50-c', text: 'A CSS preprocessor', isCorrect: false },
      { id: 'q50-d', text: 'A testing framework', isCorrect: false },
    ],
    explanation: 'JSX (JavaScript XML) is a syntax extension for JavaScript that allows you to write HTML-like markup inside JavaScript files. It is transpiled to regular JavaScript function calls (React.createElement) by tools like Babel.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-51',
    quizId: 'quiz-7',
    categoryId: 'cat-3',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is the purpose of the "key" prop in React lists?',
    options: [
      { id: 'q51-a', text: 'To encrypt list data', isCorrect: false },
      { id: 'q51-b', text: 'To help React identify which items have changed, been added, or removed', isCorrect: true },
      { id: 'q51-c', text: 'To set the CSS class of each item', isCorrect: false },
      { id: 'q51-d', text: 'To define the order of rendering', isCorrect: false },
    ],
    explanation: 'The "key" prop helps React identify which items in a list have changed, been added, or removed. Keys should be stable, unique, and predictable to allow React to efficiently update the DOM.',
    points: 15,
    timeLimit: 45,
  },

  // ---------------------------------------------------------------------------
  // PYTHON BASICS (quiz-8) — q-52 through q-58
  // ---------------------------------------------------------------------------
  {
    id: 'q-52',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the output of: print(type([]))?',
    options: [
      { id: 'q52-a', text: "<class 'array'>", isCorrect: false },
      { id: 'q52-b', text: "<class 'list'>", isCorrect: true },
      { id: 'q52-c', text: "<class 'tuple'>", isCorrect: false },
      { id: 'q52-d', text: "<class 'dict'>", isCorrect: false },
    ],
    explanation: 'In Python, [] creates an empty list. The type() function returns <class \'list\'> for list objects. Python uses "list" not "array" for its built-in sequence type.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-53',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'Which keyword is used to define a function in Python?',
    options: [
      { id: 'q53-a', text: 'function', isCorrect: false },
      { id: 'q53-b', text: 'func', isCorrect: false },
      { id: 'q53-c', text: 'def', isCorrect: true },
      { id: 'q53-d', text: 'define', isCorrect: false },
    ],
    explanation: 'In Python, the "def" keyword is used to define a function. The syntax is: def function_name(parameters): followed by an indented function body.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-54',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'true-false',
    text: 'Python uses indentation to define code blocks instead of curly braces.',
    options: [
      { id: 'q54-a', text: 'True', isCorrect: true },
      { id: 'q54-b', text: 'False', isCorrect: false },
    ],
    explanation: 'Python uses indentation (whitespace) to define code blocks, unlike languages like JavaScript or C which use curly braces {}. This is one of Python\'s most distinctive features and enforces readable code.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-55',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What does the "self" parameter in a Python class method refer to?',
    options: [
      { id: 'q55-a', text: 'The class itself', isCorrect: false },
      { id: 'q55-b', text: 'The current instance of the class', isCorrect: true },
      { id: 'q55-c', text: 'The parent class', isCorrect: false },
      { id: 'q55-d', text: 'A global variable', isCorrect: false },
    ],
    explanation: 'In Python, "self" refers to the current instance of the class. It is used to access instance variables and methods. While "self" is a convention (not a keyword), it is strongly recommended to use it.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-56',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'multi-select',
    text: 'Which of the following are immutable data types in Python? (Select all that apply)',
    options: [
      { id: 'q56-a', text: 'tuple', isCorrect: true },
      { id: 'q56-b', text: 'list', isCorrect: false },
      { id: 'q56-c', text: 'string', isCorrect: true },
      { id: 'q56-d', text: 'frozenset', isCorrect: true },
    ],
    explanation: 'Tuples, strings, and frozensets are immutable in Python, meaning their values cannot be changed after creation. Lists are mutable and can be modified in place.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-57',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is a list comprehension in Python?',
    options: [
      { id: 'q57-a', text: 'A way to sort a list', isCorrect: false },
      { id: 'q57-b', text: 'A concise way to create lists based on existing iterables', isCorrect: true },
      { id: 'q57-c', text: 'A method to delete list elements', isCorrect: false },
      { id: 'q57-d', text: 'A technique for merging two lists', isCorrect: false },
    ],
    explanation: 'A list comprehension provides a concise way to create lists. The syntax is [expression for item in iterable if condition]. For example, [x**2 for x in range(5)] creates [0, 1, 4, 9, 16].',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-58',
    quizId: 'quiz-8',
    categoryId: 'cat-3',
    difficulty: 'easy',
    type: 'true-false',
    text: 'In Python 3, the print statement does not require parentheses.',
    options: [
      { id: 'q58-a', text: 'True', isCorrect: false },
      { id: 'q58-b', text: 'False', isCorrect: true },
    ],
    explanation: 'In Python 3, print is a function and requires parentheses: print("Hello"). In Python 2, print was a statement and parentheses were optional. This is one of the major differences between Python 2 and 3.',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // WORLD WAR II (quiz-9) — q-59 through q-65
  // ---------------------------------------------------------------------------
  {
    id: 'q-59',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'In what year did World War II begin?',
    options: [
      { id: 'q59-a', text: '1937', isCorrect: false },
      { id: 'q59-b', text: '1938', isCorrect: false },
      { id: 'q59-c', text: '1939', isCorrect: true },
      { id: 'q59-d', text: '1941', isCorrect: false },
    ],
    explanation: 'World War II began on September 1, 1939, when Nazi Germany invaded Poland. Britain and France declared war on Germany two days later.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-60',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What was the code name for the Allied invasion of Normandy on June 6, 1944?',
    options: [
      { id: 'q60-a', text: 'Operation Barbarossa', isCorrect: false },
      { id: 'q60-b', text: 'Operation Overlord', isCorrect: true },
      { id: 'q60-c', text: 'Operation Market Garden', isCorrect: false },
      { id: 'q60-d', text: 'Operation Torch', isCorrect: false },
    ],
    explanation: 'The Allied invasion of Normandy was code-named Operation Overlord. D-Day, June 6, 1944, was the largest seaborne invasion in history, marking the beginning of the liberation of Western Europe.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-61',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'true-false',
    text: 'The atomic bombs were dropped on Hiroshima and Nagasaki in August 1945.',
    options: [
      { id: 'q61-a', text: 'True', isCorrect: true },
      { id: 'q61-b', text: 'False', isCorrect: false },
    ],
    explanation: 'The United States dropped an atomic bomb on Hiroshima on August 6, 1945, and on Nagasaki on August 9, 1945. Japan announced its surrender on August 15, 1945.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-62',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'Which country was NOT part of the Allied Powers during WWII?',
    options: [
      { id: 'q62-a', text: 'United Kingdom', isCorrect: false },
      { id: 'q62-b', text: 'Soviet Union', isCorrect: false },
      { id: 'q62-c', text: 'Italy', isCorrect: true },
      { id: 'q62-d', text: 'United States', isCorrect: false },
    ],
    explanation: 'Italy was originally part of the Axis Powers along with Germany and Japan. Italy switched sides in 1943 after the fall of Mussolini, but it was initially an Axis power, not an Allied power.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-63',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What was the Battle of Stalingrad significant for?',
    options: [
      { id: 'q63-a', text: 'It was the first battle of WWII', isCorrect: false },
      { id: 'q63-b', text: 'It marked a major turning point on the Eastern Front', isCorrect: true },
      { id: 'q63-c', text: 'It was where the atomic bomb was first tested', isCorrect: false },
      { id: 'q63-d', text: 'It was the last battle of WWII', isCorrect: false },
    ],
    explanation: 'The Battle of Stalingrad (August 1942 - February 1943) was a major turning point on the Eastern Front. The Soviet victory marked the beginning of the German retreat and is considered one of the bloodiest battles in history.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-64',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'multi-select',
    text: 'Which of the following were Axis Powers during WWII? (Select all that apply)',
    options: [
      { id: 'q64-a', text: 'Germany', isCorrect: true },
      { id: 'q64-b', text: 'France', isCorrect: false },
      { id: 'q64-c', text: 'Japan', isCorrect: true },
      { id: 'q64-d', text: 'Italy', isCorrect: true },
    ],
    explanation: 'The three main Axis Powers were Germany, Japan, and Italy. France was an Allied Power, though it was occupied by Germany from 1940 to 1944.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-65',
    quizId: 'quiz-9',
    categoryId: 'cat-4',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What event directly caused the United States to enter World War II?',
    options: [
      { id: 'q65-a', text: 'The invasion of Poland', isCorrect: false },
      { id: 'q65-b', text: 'The attack on Pearl Harbor', isCorrect: true },
      { id: 'q65-c', text: 'The sinking of the Lusitania', isCorrect: false },
      { id: 'q65-d', text: 'The Battle of Britain', isCorrect: false },
    ],
    explanation: 'The Japanese attack on Pearl Harbor, Hawaii, on December 7, 1941, directly led to the United States declaring war on Japan the following day, and subsequently entering World War II.',
    points: 10,
    timeLimit: 30,
  },

  // ---------------------------------------------------------------------------
  // ANCIENT CIVILIZATIONS (quiz-10) — q-66 through q-71
  // ---------------------------------------------------------------------------
  {
    id: 'q-66',
    quizId: 'quiz-10',
    categoryId: 'cat-4',
    difficulty: 'expert',
    type: 'multiple-choice',
    text: 'Which ancient civilization built the Great Pyramids of Giza?',
    options: [
      { id: 'q66-a', text: 'Roman Empire', isCorrect: false },
      { id: 'q66-b', text: 'Ancient Egypt', isCorrect: true },
      { id: 'q66-c', text: 'Mesopotamia', isCorrect: false },
      { id: 'q66-d', text: 'Ancient Greece', isCorrect: false },
    ],
    explanation: 'The Great Pyramids of Giza were built by the ancient Egyptians during the Old Kingdom period, around 2560 BCE. The largest, the Great Pyramid, was built for Pharaoh Khufu.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-67',
    quizId: 'quiz-10',
    categoryId: 'cat-4',
    difficulty: 'expert',
    type: 'multiple-choice',
    text: 'What writing system did the ancient Sumerians develop?',
    options: [
      { id: 'q67-a', text: 'Hieroglyphics', isCorrect: false },
      { id: 'q67-b', text: 'Cuneiform', isCorrect: true },
      { id: 'q67-c', text: 'Sanskrit', isCorrect: false },
      { id: 'q67-d', text: 'Linear B', isCorrect: false },
    ],
    explanation: 'The ancient Sumerians of Mesopotamia developed cuneiform, one of the earliest known writing systems. It was written by pressing a wedge-shaped stylus into clay tablets.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-68',
    quizId: 'quiz-10',
    categoryId: 'cat-4',
    difficulty: 'expert',
    type: 'true-false',
    text: 'The Roman Empire fell in 476 AD when the last Western Roman Emperor was deposed.',
    options: [
      { id: 'q68-a', text: 'True', isCorrect: true },
      { id: 'q68-b', text: 'False', isCorrect: false },
    ],
    explanation: 'The traditional date for the fall of the Western Roman Empire is 476 AD, when the Germanic chieftain Odoacer deposed the last Western Roman Emperor, Romulus Augustulus. The Eastern Roman Empire (Byzantine Empire) continued until 1453.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-69',
    quizId: 'quiz-10',
    categoryId: 'cat-4',
    difficulty: 'expert',
    type: 'multiple-choice',
    text: 'Which ancient Greek city-state was known for its military society and warriors?',
    options: [
      { id: 'q69-a', text: 'Athens', isCorrect: false },
      { id: 'q69-b', text: 'Corinth', isCorrect: false },
      { id: 'q69-c', text: 'Sparta', isCorrect: true },
      { id: 'q69-d', text: 'Thebes', isCorrect: false },
    ],
    explanation: 'Sparta was renowned for its military-focused society. Spartan boys began military training at age 7 (the agoge system), and Sparta\'s warriors were considered among the finest soldiers in the ancient world.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-70',
    quizId: 'quiz-10',
    categoryId: 'cat-4',
    difficulty: 'expert',
    type: 'multi-select',
    text: 'Which of the following are considered Ancient Wonders of the World? (Select all that apply)',
    options: [
      { id: 'q70-a', text: 'Great Pyramid of Giza', isCorrect: true },
      { id: 'q70-b', text: 'Colosseum of Rome', isCorrect: false },
      { id: 'q70-c', text: 'Hanging Gardens of Babylon', isCorrect: true },
      { id: 'q70-d', text: 'Lighthouse of Alexandria', isCorrect: true },
    ],
    explanation: 'The Seven Wonders of the Ancient World include the Great Pyramid of Giza, the Hanging Gardens of Babylon, and the Lighthouse of Alexandria. The Colosseum was built later and is not on the ancient list.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-71',
    quizId: 'quiz-10',
    categoryId: 'cat-4',
    difficulty: 'expert',
    type: 'multiple-choice',
    text: 'The Indus Valley Civilization was located in present-day:',
    options: [
      { id: 'q71-a', text: 'Egypt and Sudan', isCorrect: false },
      { id: 'q71-b', text: 'Pakistan and northwestern India', isCorrect: true },
      { id: 'q71-c', text: 'Iraq and Syria', isCorrect: false },
      { id: 'q71-d', text: 'China and Mongolia', isCorrect: false },
    ],
    explanation: 'The Indus Valley Civilization (c. 3300-1300 BCE) was located in present-day Pakistan and northwestern India along the Indus River. Major cities included Harappa and Mohenjo-daro.',
    points: 15,
    timeLimit: 45,
  },

  // ---------------------------------------------------------------------------
  // ENGLISH GRAMMAR (quiz-11) — q-72 through q-77
  // ---------------------------------------------------------------------------
  {
    id: 'q-72',
    quizId: 'quiz-11',
    categoryId: 'cat-5',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'Which sentence uses the correct form of "their/there/they\'re"?',
    options: [
      { id: 'q72-a', text: 'Their going to the store.', isCorrect: false },
      { id: 'q72-b', text: 'They\'re going to the store.', isCorrect: true },
      { id: 'q72-c', text: 'There going to the store.', isCorrect: false },
      { id: 'q72-d', text: 'Ther going to the store.', isCorrect: false },
    ],
    explanation: '"They\'re" is the contraction of "they are." "Their" is the possessive form (their books), and "there" refers to a place (over there). "They\'re going to the store" = "They are going to the store."',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-73',
    quizId: 'quiz-11',
    categoryId: 'cat-5',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What part of speech is the word "quickly" in the sentence "She ran quickly"?',
    options: [
      { id: 'q73-a', text: 'Adjective', isCorrect: false },
      { id: 'q73-b', text: 'Adverb', isCorrect: true },
      { id: 'q73-c', text: 'Verb', isCorrect: false },
      { id: 'q73-d', text: 'Noun', isCorrect: false },
    ],
    explanation: '"Quickly" is an adverb because it modifies the verb "ran," describing how the action was performed. Adverbs typically modify verbs, adjectives, or other adverbs.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-74',
    quizId: 'quiz-11',
    categoryId: 'cat-5',
    difficulty: 'medium',
    type: 'true-false',
    text: 'A semicolon can be used to join two independent clauses that are closely related.',
    options: [
      { id: 'q74-a', text: 'True', isCorrect: true },
      { id: 'q74-b', text: 'False', isCorrect: false },
    ],
    explanation: 'A semicolon can join two independent clauses that are closely related in meaning without a coordinating conjunction. Example: "I have a test tomorrow; I need to study tonight."',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-75',
    quizId: 'quiz-11',
    categoryId: 'cat-5',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'Which sentence is in the passive voice?',
    options: [
      { id: 'q75-a', text: 'The cat chased the mouse.', isCorrect: false },
      { id: 'q75-b', text: 'The mouse was chased by the cat.', isCorrect: true },
      { id: 'q75-c', text: 'The cat is chasing the mouse.', isCorrect: false },
      { id: 'q75-d', text: 'The cat will chase the mouse.', isCorrect: false },
    ],
    explanation: '"The mouse was chased by the cat" is in passive voice because the subject (mouse) receives the action rather than performing it. Passive voice uses a form of "to be" plus the past participle.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-76',
    quizId: 'quiz-11',
    categoryId: 'cat-5',
    difficulty: 'medium',
    type: 'multi-select',
    text: 'Which of the following are coordinating conjunctions (FANBOYS)? (Select all that apply)',
    options: [
      { id: 'q76-a', text: 'for', isCorrect: true },
      { id: 'q76-b', text: 'because', isCorrect: false },
      { id: 'q76-c', text: 'but', isCorrect: true },
      { id: 'q76-d', text: 'yet', isCorrect: true },
    ],
    explanation: 'The FANBOYS coordinating conjunctions are: For, And, Nor, But, Or, Yet, So. "Because" is a subordinating conjunction, not a coordinating one.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-77',
    quizId: 'quiz-11',
    categoryId: 'cat-5',
    difficulty: 'medium',
    type: 'multiple-choice',
    text: 'What is a dangling modifier?',
    options: [
      { id: 'q77-a', text: 'A modifier placed at the end of a sentence', isCorrect: false },
      { id: 'q77-b', text: 'A modifier that does not clearly refer to the word it is intended to modify', isCorrect: true },
      { id: 'q77-c', text: 'An adjective used as a noun', isCorrect: false },
      { id: 'q77-d', text: 'A verb used without a subject', isCorrect: false },
    ],
    explanation: 'A dangling modifier is a phrase or clause that does not clearly and logically relate to the word or phrase it modifies. Example: "Running to the bus, my coffee spilled" (the coffee was not running).',
    points: 15,
    timeLimit: 45,
  },

  // ---------------------------------------------------------------------------
  // GENERAL TRIVIA (quiz-12) — q-78 through q-83
  // ---------------------------------------------------------------------------
  {
    id: 'q-78',
    quizId: 'quiz-12',
    categoryId: 'cat-6',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the largest ocean on Earth?',
    options: [
      { id: 'q78-a', text: 'Atlantic Ocean', isCorrect: false },
      { id: 'q78-b', text: 'Indian Ocean', isCorrect: false },
      { id: 'q78-c', text: 'Pacific Ocean', isCorrect: true },
      { id: 'q78-d', text: 'Arctic Ocean', isCorrect: false },
    ],
    explanation: 'The Pacific Ocean is the largest and deepest ocean on Earth, covering approximately 165.25 million square kilometers. It covers more area than all of the land on Earth combined.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-79',
    quizId: 'quiz-12',
    categoryId: 'cat-6',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'Which planet is known as the Red Planet?',
    options: [
      { id: 'q79-a', text: 'Venus', isCorrect: false },
      { id: 'q79-b', text: 'Mars', isCorrect: true },
      { id: 'q79-c', text: 'Jupiter', isCorrect: false },
      { id: 'q79-d', text: 'Saturn', isCorrect: false },
    ],
    explanation: 'Mars is known as the Red Planet due to the iron oxide (rust) prevalent on its surface, which gives it a reddish appearance visible from Earth.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-80',
    quizId: 'quiz-12',
    categoryId: 'cat-6',
    difficulty: 'easy',
    type: 'true-false',
    text: 'The Great Wall of China is visible from space with the naked eye.',
    options: [
      { id: 'q80-a', text: 'True', isCorrect: false },
      { id: 'q80-b', text: 'False', isCorrect: true },
    ],
    explanation: 'This is a common myth. The Great Wall of China is not visible from space with the naked eye. While it is very long (over 21,000 km), it is relatively narrow (about 5-8 meters wide), making it too thin to see from orbit.',
    points: 15,
    timeLimit: 45,
  },
  {
    id: 'q-81',
    quizId: 'quiz-12',
    categoryId: 'cat-6',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'What is the hardest natural substance on Earth?',
    options: [
      { id: 'q81-a', text: 'Gold', isCorrect: false },
      { id: 'q81-b', text: 'Iron', isCorrect: false },
      { id: 'q81-c', text: 'Diamond', isCorrect: true },
      { id: 'q81-d', text: 'Quartz', isCorrect: false },
    ],
    explanation: 'Diamond is the hardest known natural substance, rating 10 on the Mohs hardness scale. It is a form of carbon where atoms are arranged in a crystal structure called diamond cubic.',
    points: 10,
    timeLimit: 30,
  },
  {
    id: 'q-82',
    quizId: 'quiz-12',
    categoryId: 'cat-6',
    difficulty: 'easy',
    type: 'multi-select',
    text: 'Which of the following countries are in South America? (Select all that apply)',
    options: [
      { id: 'q82-a', text: 'Brazil', isCorrect: true },
      { id: 'q82-b', text: 'Portugal', isCorrect: false },
      { id: 'q82-c', text: 'Chile', isCorrect: true },
      { id: 'q82-d', text: 'Colombia', isCorrect: true },
    ],
    explanation: 'Brazil, Chile, and Colombia are all countries in South America. Portugal is a country in Europe, located on the Iberian Peninsula.',
    points: 20,
    timeLimit: 60,
  },
  {
    id: 'q-83',
    quizId: 'quiz-12',
    categoryId: 'cat-6',
    difficulty: 'easy',
    type: 'multiple-choice',
    text: 'How many bones are in the adult human body?',
    options: [
      { id: 'q83-a', text: '186', isCorrect: false },
      { id: 'q83-b', text: '206', isCorrect: true },
      { id: 'q83-c', text: '256', isCorrect: false },
      { id: 'q83-d', text: '300', isCorrect: false },
    ],
    explanation: 'An adult human body has 206 bones. Babies are born with about 270 bones, but many fuse together during growth. The smallest bone is the stapes in the ear.',
    points: 10,
    timeLimit: 30,
  },
];

// =============================================================================
// QUIZZES
// =============================================================================

export const quizzes: Quiz[] = [
  {
    id: 'quiz-1',
    title: 'Physics Fundamentals',
    description: 'Test your knowledge of basic physics concepts including motion, forces, and energy.',
    categoryId: 'cat-1',
    difficulty: 'medium',
    status: 'published',
    coverImage: '',
    questions: ['q-1', 'q-2', 'q-3', 'q-4', 'q-5', 'q-6', 'q-7', 'q-8'],
    totalQuestions: 8,
    timeLimit: 15,
    passingScore: 60,
    attempts: 234,
    rating: 4.5,
    createdBy: 'user-2',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
    tags: ['physics', 'science', 'fundamentals'],
  },
  {
    id: 'quiz-2',
    title: 'Chemistry Basics',
    description: 'Explore the foundations of chemistry including elements, compounds, and chemical reactions.',
    categoryId: 'cat-1',
    difficulty: 'easy',
    status: 'published',
    coverImage: '',
    questions: ['q-9', 'q-10', 'q-11', 'q-12', 'q-13', 'q-14', 'q-15', 'q-16'],
    totalQuestions: 8,
    timeLimit: 12,
    passingScore: 60,
    attempts: 312,
    rating: 4.3,
    createdBy: 'user-2',
    createdAt: '2024-02-03T10:00:00Z',
    updatedAt: '2024-02-18T10:00:00Z',
    tags: ['chemistry', 'science', 'basics'],
  },
  {
    id: 'quiz-3',
    title: 'Biology 101',
    description: 'Learn about cells, genetics, and the fundamentals of life sciences.',
    categoryId: 'cat-1',
    difficulty: 'easy',
    status: 'published',
    coverImage: '',
    questions: ['q-17', 'q-18', 'q-19', 'q-20', 'q-21', 'q-22', 'q-23'],
    totalQuestions: 7,
    timeLimit: 10,
    passingScore: 60,
    attempts: 287,
    rating: 4.6,
    createdBy: 'user-2',
    createdAt: '2024-02-05T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
    tags: ['biology', 'science', 'cells', 'genetics'],
  },
  {
    id: 'quiz-4',
    title: 'Algebra Essentials',
    description: 'Challenge yourself with algebraic equations, functions, and mathematical reasoning.',
    categoryId: 'cat-2',
    difficulty: 'medium',
    status: 'published',
    coverImage: '',
    questions: ['q-24', 'q-25', 'q-26', 'q-27', 'q-28', 'q-29', 'q-30'],
    totalQuestions: 7,
    timeLimit: 15,
    passingScore: 60,
    attempts: 189,
    rating: 4.2,
    createdBy: 'user-5',
    createdAt: '2024-02-07T10:00:00Z',
    updatedAt: '2024-02-22T10:00:00Z',
    tags: ['algebra', 'math', 'equations'],
  },
  {
    id: 'quiz-5',
    title: 'Geometry Challenge',
    description: 'Test your understanding of shapes, areas, volumes, and geometric theorems.',
    categoryId: 'cat-2',
    difficulty: 'hard',
    status: 'published',
    coverImage: '',
    questions: ['q-31', 'q-32', 'q-33', 'q-34', 'q-35', 'q-36'],
    totalQuestions: 6,
    timeLimit: 12,
    passingScore: 65,
    attempts: 156,
    rating: 4.0,
    createdBy: 'user-5',
    createdAt: '2024-02-09T10:00:00Z',
    updatedAt: '2024-02-24T10:00:00Z',
    tags: ['geometry', 'math', 'shapes'],
  },
  {
    id: 'quiz-6',
    title: 'JavaScript Mastery',
    description: 'Prove your JavaScript knowledge from basics to advanced concepts.',
    categoryId: 'cat-3',
    difficulty: 'hard',
    status: 'published',
    coverImage: '',
    questions: ['q-37', 'q-38', 'q-39', 'q-40', 'q-41', 'q-42', 'q-43', 'q-44'],
    totalQuestions: 8,
    timeLimit: 20,
    passingScore: 65,
    attempts: 421,
    rating: 4.7,
    createdBy: 'user-5',
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-02-25T10:00:00Z',
    tags: ['javascript', 'programming', 'web'],
  },
  {
    id: 'quiz-7',
    title: 'React Fundamentals',
    description: 'Test your understanding of React concepts including hooks, components, and state management.',
    categoryId: 'cat-3',
    difficulty: 'medium',
    status: 'published',
    coverImage: '',
    questions: ['q-45', 'q-46', 'q-47', 'q-48', 'q-49', 'q-50', 'q-51'],
    totalQuestions: 7,
    timeLimit: 15,
    passingScore: 60,
    attempts: 356,
    rating: 4.8,
    createdBy: 'user-5',
    createdAt: '2024-02-12T10:00:00Z',
    updatedAt: '2024-02-27T10:00:00Z',
    tags: ['react', 'programming', 'frontend'],
  },
  {
    id: 'quiz-8',
    title: 'Python Basics',
    description: 'Explore Python programming fundamentals including data types, functions, and OOP.',
    categoryId: 'cat-3',
    difficulty: 'easy',
    status: 'published',
    coverImage: '',
    questions: ['q-52', 'q-53', 'q-54', 'q-55', 'q-56', 'q-57', 'q-58'],
    totalQuestions: 7,
    timeLimit: 10,
    passingScore: 60,
    attempts: 489,
    rating: 4.9,
    createdBy: 'user-1',
    createdAt: '2024-02-14T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    tags: ['python', 'programming', 'basics'],
  },
  {
    id: 'quiz-9',
    title: 'World War II',
    description: 'Test your knowledge of the major events, battles, and figures of World War II.',
    categoryId: 'cat-4',
    difficulty: 'medium',
    status: 'published',
    coverImage: '',
    questions: ['q-59', 'q-60', 'q-61', 'q-62', 'q-63', 'q-64', 'q-65'],
    totalQuestions: 7,
    timeLimit: 12,
    passingScore: 60,
    attempts: 198,
    rating: 4.4,
    createdBy: 'user-1',
    createdAt: '2024-02-16T10:00:00Z',
    updatedAt: '2024-03-02T10:00:00Z',
    tags: ['wwii', 'history', 'war'],
  },
  {
    id: 'quiz-10',
    title: 'Ancient Civilizations',
    description: 'Journey through ancient Egypt, Greece, Rome, and Mesopotamia.',
    categoryId: 'cat-4',
    difficulty: 'expert',
    status: 'published',
    coverImage: '',
    questions: ['q-66', 'q-67', 'q-68', 'q-69', 'q-70', 'q-71'],
    totalQuestions: 6,
    timeLimit: 10,
    passingScore: 70,
    attempts: 87,
    rating: 4.1,
    createdBy: 'user-1',
    createdAt: '2024-02-18T10:00:00Z',
    updatedAt: '2024-03-03T10:00:00Z',
    tags: ['ancient', 'history', 'civilizations'],
  },
  {
    id: 'quiz-11',
    title: 'English Grammar',
    description: 'Master English grammar rules including punctuation, parts of speech, and sentence structure.',
    categoryId: 'cat-5',
    difficulty: 'medium',
    status: 'published',
    coverImage: '',
    questions: ['q-72', 'q-73', 'q-74', 'q-75', 'q-76', 'q-77'],
    totalQuestions: 6,
    timeLimit: 10,
    passingScore: 60,
    attempts: 145,
    rating: 3.9,
    createdBy: 'user-2',
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-03-04T10:00:00Z',
    tags: ['english', 'grammar', 'language'],
  },
  {
    id: 'quiz-12',
    title: 'General Trivia',
    description: 'A fun mix of questions covering geography, science, culture, and more.',
    categoryId: 'cat-6',
    difficulty: 'easy',
    status: 'published',
    coverImage: '',
    questions: ['q-78', 'q-79', 'q-80', 'q-81', 'q-82', 'q-83'],
    totalQuestions: 6,
    timeLimit: 8,
    passingScore: 50,
    attempts: 502,
    rating: 4.6,
    createdBy: 'user-1',
    createdAt: '2024-02-22T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
    tags: ['trivia', 'general', 'fun'],
  },
];

// =============================================================================
// QUIZ ATTEMPTS
// =============================================================================

export const quizAttempts: QuizAttempt[] = [
  { id: 'attempt-1', quizId: 'quiz-1', userId: 'user-1', status: 'completed', answers: [], score: 70, percentage: 85, passed: true, startedAt: '2024-02-20T10:00:00Z', completedAt: '2024-02-20T10:12:00Z', timeTaken: 720 },
  { id: 'attempt-2', quizId: 'quiz-6', userId: 'user-1', status: 'completed', answers: [], score: 74, percentage: 92, passed: true, startedAt: '2024-02-21T14:00:00Z', completedAt: '2024-02-21T14:15:00Z', timeTaken: 900 },
  { id: 'attempt-3', quizId: 'quiz-7', userId: 'user-1', status: 'completed', answers: [], score: 70, percentage: 100, passed: true, startedAt: '2024-02-22T09:00:00Z', completedAt: '2024-02-22T09:10:00Z', timeTaken: 600 },
  { id: 'attempt-4', quizId: 'quiz-4', userId: 'user-1', status: 'completed', answers: [], score: 50, percentage: 71, passed: true, startedAt: '2024-02-23T11:00:00Z', completedAt: '2024-02-23T11:14:00Z', timeTaken: 840 },
  { id: 'attempt-5', quizId: 'quiz-9', userId: 'user-1', status: 'timed-out', answers: [], score: 30, percentage: 42, passed: false, startedAt: '2024-02-24T15:00:00Z', completedAt: '2024-02-24T15:20:00Z', timeTaken: 1200 },
  { id: 'attempt-6', quizId: 'quiz-2', userId: 'user-2', status: 'completed', answers: [], score: 80, percentage: 100, passed: true, startedAt: '2024-02-18T09:00:00Z', completedAt: '2024-02-18T09:08:00Z', timeTaken: 480 },
  { id: 'attempt-7', quizId: 'quiz-3', userId: 'user-2', status: 'completed', answers: [], score: 60, percentage: 86, passed: true, startedAt: '2024-02-19T10:00:00Z', completedAt: '2024-02-19T10:09:00Z', timeTaken: 540 },
  { id: 'attempt-8', quizId: 'quiz-1', userId: 'user-2', status: 'completed', answers: [], score: 60, percentage: 75, passed: true, startedAt: '2024-02-20T14:00:00Z', completedAt: '2024-02-20T14:11:00Z', timeTaken: 660 },
  { id: 'attempt-9', quizId: 'quiz-8', userId: 'user-3', status: 'completed', answers: [], score: 50, percentage: 71, passed: true, startedAt: '2024-02-22T10:00:00Z', completedAt: '2024-02-22T10:07:00Z', timeTaken: 420 },
  { id: 'attempt-10', quizId: 'quiz-4', userId: 'user-3', status: 'completed', answers: [], score: 60, percentage: 86, passed: true, startedAt: '2024-02-23T14:00:00Z', completedAt: '2024-02-23T14:12:00Z', timeTaken: 720 },
  { id: 'attempt-11', quizId: 'quiz-5', userId: 'user-3', status: 'timed-out', answers: [], score: 30, percentage: 50, passed: false, startedAt: '2024-02-25T09:00:00Z', completedAt: '2024-02-25T09:15:00Z', timeTaken: 900 },
  { id: 'attempt-12', quizId: 'quiz-10', userId: 'user-4', status: 'completed', answers: [], score: 40, percentage: 67, passed: true, startedAt: '2024-02-20T11:00:00Z', completedAt: '2024-02-20T11:18:00Z', timeTaken: 1080 },
  { id: 'attempt-13', quizId: 'quiz-9', userId: 'user-4', status: 'completed', answers: [], score: 50, percentage: 71, passed: true, startedAt: '2024-02-21T15:00:00Z', completedAt: '2024-02-21T15:13:00Z', timeTaken: 780 },
  { id: 'attempt-14', quizId: 'quiz-6', userId: 'user-5', status: 'completed', answers: [], score: 80, percentage: 100, passed: true, startedAt: '2024-02-19T09:00:00Z', completedAt: '2024-02-19T09:10:00Z', timeTaken: 600 },
  { id: 'attempt-15', quizId: 'quiz-7', userId: 'user-5', status: 'completed', answers: [], score: 70, percentage: 100, passed: true, startedAt: '2024-02-20T10:00:00Z', completedAt: '2024-02-20T10:08:00Z', timeTaken: 480 },
  { id: 'attempt-16', quizId: 'quiz-8', userId: 'user-5', status: 'completed', answers: [], score: 60, percentage: 86, passed: true, startedAt: '2024-02-21T14:00:00Z', completedAt: '2024-02-21T14:07:00Z', timeTaken: 420 },
  { id: 'attempt-17', quizId: 'quiz-11', userId: 'user-6', status: 'completed', answers: [], score: 40, percentage: 67, passed: true, startedAt: '2024-02-25T10:00:00Z', completedAt: '2024-02-25T10:09:00Z', timeTaken: 540 },
  { id: 'attempt-18', quizId: 'quiz-12', userId: 'user-6', status: 'completed', answers: [], score: 50, percentage: 83, passed: true, startedAt: '2024-02-26T11:00:00Z', completedAt: '2024-02-26T11:06:00Z', timeTaken: 360 },
  { id: 'attempt-19', quizId: 'quiz-1', userId: 'user-3', status: 'timed-out', answers: [], score: 40, percentage: 50, passed: false, startedAt: '2024-03-01T09:00:00Z', completedAt: '2024-03-01T09:15:00Z', timeTaken: 900 },
  { id: 'attempt-20', quizId: 'quiz-12', userId: 'user-4', status: 'completed', answers: [], score: 50, percentage: 83, passed: true, startedAt: '2024-03-04T09:00:00Z', completedAt: '2024-03-04T09:11:00Z', timeTaken: 660 },
]

// =============================================================================
// LEADERBOARD
// =============================================================================

export const leaderboard: LeaderboardEntry[] = [
  { userId: 'user-1', name: 'Alex Thompson', avatar: '', totalScore: 12500, quizzesTaken: 45, averageScore: 88, rank: 1, trend: 'same' },
  { userId: 'user-2', name: 'Sarah Chen', avatar: '', totalScore: 11200, quizzesTaken: 38, averageScore: 92, rank: 2, trend: 'up' },
  { userId: 'user-5', name: 'David Kim', avatar: '', totalScore: 10800, quizzesTaken: 41, averageScore: 94, rank: 3, trend: 'up' },
  { userId: 'user-3', name: 'James Wilson', avatar: '', totalScore: 8400, quizzesTaken: 29, averageScore: 76, rank: 4, trend: 'down' },
  { userId: 'user-4', name: 'Maria Garcia', avatar: '', totalScore: 7600, quizzesTaken: 22, averageScore: 81, rank: 5, trend: 'up' },
  { userId: 'user-6', name: 'Emily Johnson', avatar: '', totalScore: 6200, quizzesTaken: 18, averageScore: 85, rank: 6, trend: 'same' },
  { userId: 'user-7', name: 'Ryan Park', avatar: '', totalScore: 4800, quizzesTaken: 15, averageScore: 70, rank: 7, trend: 'down' },
  { userId: 'user-8', name: 'Olivia Brown', avatar: '', totalScore: 3500, quizzesTaken: 12, averageScore: 68, rank: 8, trend: 'same' },
];

// =============================================================================
// ACHIEVEMENTS
// =============================================================================

export const achievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Quiz',
    description: 'Complete your first quiz',
    icon: 'Trophy',
    category: 'milestone',
    status: 'unlocked',
    progress: 1,
    maxProgress: 1,
    unlockedAt: '2024-02-01T10:00:00Z',
    points: 50,
  },
  {
    id: 'ach-2',
    title: 'Quiz Master',
    description: 'Complete 10 quizzes',
    icon: 'Award',
    category: 'milestone',
    status: 'in-progress',
    progress: 5,
    maxProgress: 10,
    points: 200,
  },
  {
    id: 'ach-3',
    title: 'Perfect Score',
    description: 'Score 100% on any quiz',
    icon: 'Star',
    category: 'performance',
    status: 'unlocked',
    progress: 1,
    maxProgress: 1,
    unlockedAt: '2024-02-20T15:00:00Z',
    points: 100,
  },
  {
    id: 'ach-4',
    title: 'Speed Demon',
    description: 'Complete a quiz in under 3 minutes',
    icon: 'Zap',
    category: 'speed',
    status: 'unlocked',
    progress: 1,
    maxProgress: 1,
    unlockedAt: '2024-02-25T12:00:00Z',
    points: 75,
  },
  {
    id: 'ach-5',
    title: 'Streak Starter',
    description: 'Maintain a 3-day quiz streak',
    icon: 'Flame',
    category: 'streak',
    status: 'unlocked',
    progress: 3,
    maxProgress: 3,
    unlockedAt: '2024-02-10T09:00:00Z',
    points: 100,
  },
  {
    id: 'ach-6',
    title: 'Week Warrior',
    description: 'Maintain a 7-day quiz streak',
    icon: 'Flame',
    category: 'streak',
    status: 'in-progress',
    progress: 5,
    maxProgress: 7,
    points: 200,
  },
  {
    id: 'ach-7',
    title: 'Science Whiz',
    description: 'Complete all Science category quizzes',
    icon: 'Microscope',
    category: 'category',
    status: 'in-progress',
    progress: 2,
    maxProgress: 3,
    points: 150,
  },
  {
    id: 'ach-8',
    title: 'Code Ninja',
    description: 'Score above 90% on all Programming quizzes',
    icon: 'Code',
    category: 'category',
    status: 'locked',
    progress: 0,
    maxProgress: 3,
    points: 250,
  },
  {
    id: 'ach-9',
    title: 'Social Butterfly',
    description: 'Share a quiz result with friends',
    icon: 'Share2',
    category: 'social',
    status: 'locked',
    progress: 0,
    maxProgress: 1,
    points: 50,
  },
  {
    id: 'ach-10',
    title: 'Quiz Creator',
    description: 'Create your first quiz',
    icon: 'PenTool',
    category: 'milestone',
    status: 'unlocked',
    progress: 1,
    maxProgress: 1,
    unlockedAt: '2024-02-15T14:00:00Z',
    points: 100,
  },
  {
    id: 'ach-11',
    title: 'Half Century',
    description: 'Complete 50 quizzes',
    icon: 'Medal',
    category: 'milestone',
    status: 'in-progress',
    progress: 45,
    maxProgress: 50,
    points: 500,
  },
  {
    id: 'ach-12',
    title: 'Lightning Round',
    description: 'Answer 5 questions correctly in under 30 seconds each',
    icon: 'Timer',
    category: 'speed',
    status: 'unlocked',
    progress: 5,
    maxProgress: 5,
    unlockedAt: '2024-03-01T10:00:00Z',
    points: 150,
  },
  {
    id: 'ach-13',
    title: 'History Buff',
    description: 'Complete all History category quizzes with 80%+ score',
    icon: 'BookOpen',
    category: 'category',
    status: 'in-progress',
    progress: 1,
    maxProgress: 2,
    points: 200,
  },
  {
    id: 'ach-14',
    title: 'Team Player',
    description: 'Invite 3 friends to join the platform',
    icon: 'Users',
    category: 'social',
    status: 'in-progress',
    progress: 1,
    maxProgress: 3,
    points: 100,
  },
  {
    id: 'ach-15',
    title: 'Perfectionist',
    description: 'Score 100% on 5 different quizzes',
    icon: 'Crown',
    category: 'performance',
    status: 'in-progress',
    progress: 2,
    maxProgress: 5,
    points: 300,
  },
];

// =============================================================================
// NOTIFICATIONS
// =============================================================================

export const notifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'achievement',
    title: 'Achievement Unlocked!',
    message: 'You earned the "Perfect Score" achievement by scoring 100% on React Fundamentals.',
    isRead: false,
    createdAt: '2024-03-05T08:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'quiz',
    title: 'New Quiz Available',
    message: 'A new quiz "Advanced Python" has been added to the Programming category.',
    isRead: false,
    createdAt: '2024-03-05T07:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'system',
    title: 'Platform Update',
    message: 'We have added new features including timed challenges and leaderboard improvements.',
    isRead: true,
    createdAt: '2024-03-04T12:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-2',
    type: 'quiz',
    title: 'Quiz Completed',
    message: 'Your student James Wilson completed "Physics Fundamentals" with a score of 50%.',
    isRead: false,
    createdAt: '2024-03-04T16:00:00Z',
  },
  {
    id: 'notif-5',
    userId: 'user-2',
    type: 'reminder',
    title: 'Daily Streak Reminder',
    message: 'Keep your 12-day streak alive! Take a quiz today to continue your progress.',
    isRead: true,
    createdAt: '2024-03-04T09:00:00Z',
  },
  {
    id: 'notif-6',
    userId: 'user-3',
    type: 'achievement',
    title: 'Almost There!',
    message: 'You are 2 quizzes away from earning the "Quiz Master" achievement.',
    isRead: false,
    createdAt: '2024-03-04T14:00:00Z',
  },
  {
    id: 'notif-7',
    userId: 'user-3',
    type: 'social',
    title: 'Friend Activity',
    message: 'Maria Garcia just scored 90% on "World War II". Can you beat her score?',
    isRead: true,
    createdAt: '2024-03-03T18:00:00Z',
  },
  {
    id: 'notif-8',
    userId: 'user-4',
    type: 'quiz',
    title: 'Quiz Result',
    message: 'You scored 83% on "Ancient Civilizations". Great job!',
    isRead: true,
    createdAt: '2024-02-28T11:10:00Z',
  },
  {
    id: 'notif-9',
    userId: 'user-4',
    type: 'reminder',
    title: 'Weekly Challenge',
    message: 'This week\'s challenge: Complete 3 quizzes from different categories. 2 of 3 done!',
    isRead: false,
    createdAt: '2024-03-03T10:00:00Z',
  },
  {
    id: 'notif-10',
    userId: 'user-5',
    type: 'achievement',
    title: 'Achievement Unlocked!',
    message: 'You earned the "Lightning Round" achievement for your quick answering speed.',
    isRead: true,
    createdAt: '2024-03-01T10:05:00Z',
  },
  {
    id: 'notif-11',
    userId: 'user-5',
    type: 'system',
    title: 'New Feature: Quiz Analytics',
    message: 'Check out the new analytics dashboard to track your performance trends over time.',
    isRead: false,
    createdAt: '2024-03-04T08:00:00Z',
  },
  {
    id: 'notif-12',
    userId: 'user-6',
    type: 'social',
    title: 'Leaderboard Update',
    message: 'You moved up to rank #6 on the global leaderboard! Keep it up!',
    isRead: false,
    createdAt: '2024-03-02T20:30:00Z',
  },
  {
    id: 'notif-13',
    userId: 'user-6',
    type: 'reminder',
    title: 'Streak Alert',
    message: 'Your quiz streak is at 3 days. Take a quiz today to keep it going!',
    isRead: true,
    createdAt: '2024-03-02T09:00:00Z',
  },
  {
    id: 'notif-14',
    userId: 'user-1',
    type: 'social',
    title: 'Challenge Received',
    message: 'David Kim has challenged you to beat his score on "JavaScript Mastery"!',
    isRead: false,
    createdAt: '2024-03-05T06:00:00Z',
  },
  {
    id: 'notif-15',
    userId: 'user-1',
    type: 'system',
    title: 'Scheduled Maintenance',
    message: 'The platform will undergo maintenance on March 10, 2024 from 2:00 AM to 4:00 AM UTC.',
    isRead: true,
    createdAt: '2024-03-03T12:00:00Z',
  },
];

// =============================================================================
// DASHBOARD STATS
// =============================================================================

export const dashboardStats: DashboardStats = {
  totalQuizzes: 12,
  totalQuestions: 83,
  totalUsers: 8,
  averageScore: 72,
};
